name: docyfy-ecr-stage
on:
  push:
    paths:
      - "backend/**"
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  docker_image_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      #- name: Build, tag, and push docker image to Amazon ECR
       # env:
        #  REGISTRY: ecr
         # REPOSITORY: docyfy
          #IMAGE_TAG: ${{ steps.short-sha.outputs.sha }-backend
      - name: hamza
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
       
