name: docyfy-ecr-stage
on:
  push:
    paths:
      - "frontend/**"
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  docker_image_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
     # - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ecr
          REPOSITORY: ecr-test
          IMAGE_TAG: ${{ steps.short-sha.outputs.sha }}-fr
      - name: hamza
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        
