name: docyfy-ecr-stage
on:
  push:
    paths:
      - "frontend/**"
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  docker_image_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          region: us-east-1
          REGISTRY: 712972998930.dkr.ecr.aws-region-1.amazonaws.com
          REPOSITORY: 712972998930.dkr.ecr.us-east-1.amazonaws.com/ecr
          IMAGE_TAG: ${{ github.sha }}
      - name: frontend
        run: |
            cd frontend
            sudo docker build -t hamza:latest .
            sudo docker push hamza:latest
