name: docyfy-ecr-stage
on:
  push:
    paths:
      - 'frontend/**'
      - 'backend/**'
    branches:
      - main
  pull_request:
    branches:
      - master
jobs:
  docker_image_push:
    if: steps.changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    steps:
       - name: hamza
         run: |
          echo frontend
          echo haha
    #    if: steps.changes.outputs.backend == 'true'
   #   - name: test
  #      run: |
 #          echo backend
#           echo haha
