name: docyfy-ecr-stage
on:
  push:
    paths:
      - "frontend/**"
      - "backend/**"
    branches:
      - main
  pull_request:
    branches:
      - master
jobs:
  docker_image_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'
        if: steps.filter.outputs.frontend == 'true'
      - name: hamza
        run: |
          echo frontend
          echo haha
        if: steps.filter.outputs.backend == 'true'
      - name: test
        run: |
           echo backend
           echo haha
