name: docyfy-ecr-stage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master
jobs:
 tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          backend:
            - 'backend/**'
          frontend:
            - 'frontend/**'
    - name: backend tests
      if: steps.filter.outputs.backend == 'true'
      run: echo backend

    # run only if 'frontend' files were changed
    - name: frontend tests
      if: steps.filter.outputs.frontend == 'true'
      run: echo fronted       
