name: docyfy-ecr-stage
on:
  push:
    paths:
      - "frontend/**"
      - "backend/**"
    branches:
      - main
  pull_request:
    branches:
      - master
jobs:
 tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          backend:
            - 'backend/**'
          frontend:
            - 'frontend/**'
  #  - name: backend tests
      if: steps.filter.outputs.backend == 'true'
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: hamza
      run: |
          echo bakcend
          echo backend
    # run only if 'frontend' files were changed
      if: steps.filter.outputs.frontend == 'true'
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1    
    - name: hamza
      run: |
          echo frontend
          echo front 
