name: docyfy-ecr-stage
on:
  push:
    paths:
      - "frontend/**"
      - "backend/**"
    branches:
      - main
  pull_request:
    branches:
      - master
jobs:
  docker_image_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: docyfy-stage
          REPOSITORY: docyfy
          IMAGE_TAG: ${{ steps.short-sha.outputs.sha }-fr
      - name: hamza
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
